### ISSUE TITLE
NPE when typing a fully qualified name in Symbol view

### ISSUE THREAD

**Issue by gayanper** [gayanper/gap-eclipse-plugins#3]
java.lang.NullPointerException
	at org.eclipse.jdt.internal.core.search.matching.OrPattern.<init>(OrPattern.java:34)
	at org.eclipse.jdt.core.search.SearchPattern.createOrPattern(SearchPattern.java:1393)
	at org.gap.eclipse.jdt.symbol.OpenSymbolDialog.fillContentProvider(OpenSymbolDialog.java:101)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:1927)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:1882)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:1859)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:1847)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by gayanper** [comment]
This happens when typing as follows

`ArrayList.`
